apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-worker-7756
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/gateway-worker-7756
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
